apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-webapp
  template:
    metadata:
      labels:
        app: python-webapp
    spec:
      containers:
      - name: python-webapp
        image: us-central1-docker.pkg.dev/gcp-lab-421817/github-actions/python-webapp:10
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: python-webapp-service
spec:
  selector:
    app: python-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer