# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      # Working Directory
      - name: Run a one-line script
        run: pwd
      # Test Create VM
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GITHUB_TOKENGOOGLE_APPLICATION_CREDENTIALS }}"
      # Print Service Account info
      - name: Print Service Account info
        run: |
          gcloud iam service-accounts keys list \
          --iam-account=github-actions@gcp-lab-421817.iam.gserviceaccount.com
      # - name: Run a multi-line script
      #   run: gcloud iam service-accounts keys list \
      #   --iam-account=github-actions@gcp-lab-421817.iam.gserviceaccount.com

      
