name: CD

on:
  repository_dispatch:
    types: [trigger-cd]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"

      # Set up gcloud SDK
      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2.1.0
      
      - name: Display Info about the cloud environment
        run: gcloud info

      - name: Get Kubernetes credentials
        run: |
          gcloud config set project gcp-lab-421817
          gcloud config set compute/zone us-central1-c
          gcloud components install kubectl
          gcloud container clusters get-credentials cluster-1
          
      # Deploy the application to GKE
      - name: Deploy to GKE
        run: |
          gcloud config set project gcp-lab
          gcloud config set compute/zone us-central1-c
          gcloud container clusters get-credentials cluster-1
          kubectl apply -f k8s/deployment.yaml
